# version
version: '2'

services:
    drupal: # drupal content management system
        image: drupal:8.8.2
        ports: 
            - "8080:80" # --publish 8080:80
        volumes: # use named volumes to store unique data
            - drupal-modules:/var/www/html/modules
            - drupal-profiles:/var/www/html/profiles
            - drupal-sites:/var/www/html/sites
            - drupal-themes:/var/www/html/themes
        depends_on: # depends on PostgreSQL db
            - postgres
    postgres: # db
        image: postgres:12.1
        environment: # set password
            POSTGRES_PASSWORD: mypassword
        volumes: # set named volume
            - psql-data:/var/lib/postgresql/data

# named volumes
volumes: 
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes:
    psql-data: